### ISSUE TITLE
BitBuffer doesn't behave as intended for negative hashes

### ISSUE THREAD

**Issue by chadkirby** [wiedi/node-bloem#2]
I don't think that the BitBuffer is behaving as intended when calulateHashes returns a hash with a negative value.

When you "get" or "set" a bit with a positive index from a BitBucket, you are accessing an octet from the buffer object. However, when you "get" or "set" a bit with a negative index from a BitBucket, you are accessing a property that was created on the buffer object. See the JSON.stringify output below. 

In the end, it works, but maybe this is not intended behavior? 

```
    var bf0, word, words, _i, _len;
    bf0 = new bloem.SafeBloem(5, 0.01);
    words = ["monkey", "tree", "beef", "goat", "hamburger"];
    for (_i = 0, _len = words.length; _i < _len; _i++) {
      word = words[_i];
      bf0.add(word);
    }
```

{ key: 'monkey', hashes: [ 7, 18, 29, 40, 3, 14, 25 ] }
{ key: 'tree', hashes: [ -2, -40, -30, 28, 38, 0, 10 ] }
{ key: 'beef', hashes: [ -40, -36, -32, -28, -24, -20, -16 ] }
{ key: 'goat', hashes: [ -11, -42, -25, -8, -39, -22, -5 ] }
{ key: 'hamburger', hashes: [ 21, 6, 39, 24, 9, 42, 27 ] }

```
    console.log(JSON.stringify(bf0, null, ' '));

  {
   "capacity": 5,
   "error_rate": 0.01,
   "count": 5,
   "filter": {
    "size": 48,
    "slices": 6.654212933375475,
    "bitfield": {
     "buffer": {
      "0": 201,
      "1": 70,
      "2": 36,
      "3": 59,
      "4": 192,
      "5": 5,
      "length": 6,
      "offset": 2600,
      "-1": 1207959553,
      "-5": 301989889,
      "-4": -1811939327,
      "-3": 335544321,
      "-2": 536870913,
      "-6": 1073741824
     }
    }
   }
  }
```

**Comment by chadkirby** [comment]
Possible solution, force unsigned hash value in calculateHashes:

```
function fnv(seed, data) {
    var h = new VNF()
    h.update(seed)
    h.update(data)
    return h.value() >>> 0
}
```

Alternately, force unsigned value in FNV.prototype.value:

```
value: function() {
    return (this.hash & 0xffffffff) >>> 0
}
```

**Comment by wiedi** [comment]
thanks! Merged your pull request.
